### ISSUE TITLE
Video Stats Not Updating

### ISSUE THREAD

**Issue by Nate463** [cybertron-cube/CyberVideoPlayer#35]
**Describe the bug**
When using FFprobe or Mediainfo to show stats within the media player, they don't update when dragging and dropping a new file to play.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version 24H2 Build 26100.1

**Comment by cybertron-cube** [comment]
This seems to be related to #34 and will be resolved with it.
